### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by lukewhrit**
## Changes

* Lots of cleanup
* Adds normalize.css
* Adds meta tags
* Fixes portfolio page

Should be a perfect 100/100/100/100 on Lighthouse.

### CODE REVIEW

**Comment by jackiedorland** [comment]
why tf did u close this

**Comment by lukewhrit** [comment]
@heyitspuggo bc it got out of date

**Comment by jackiedorland** [comment]
large smh

**Comment by donzal** [comment]
> large smh 

It was outed fairly fast, since I had changed around a lot of the things already.

**Pull request closed without merging**
